name: wekan
version: "0.10.1-1"
summary: The open-source Trello-like kanban
description: |
   Wekan is an open-source and collaborative kanban board application.

   Whether you’re maintaining a personal todo list, planning your holidays with some friends, or working in a team on your next revolutionary idea, Kanban boards are an unbeatable tool to keep your things organized. They give you a visual overview of the current state of your project, and make you productive by allowing you to focus on the few items that matter the most.
   depending on your environment, you might need to alter some configuration settings
   use: $ snap set wekan <key>="<key value>"
    eg $ snap set wekan PORT='8080'
   supported keys:
     - MONGO_PORT: mongodb binding port, default value is '2017'
     - MONGO_BIND_IP: mondodb binding IP address, default value is '"127.0.0.1'
     - PORT: port wekan is exposed on, default value is'8080'
     - ROOT_URL: wekan root url where wekan can be accessed, default value is 'http://127.0.0.1'
     - MAIL_URL: wekan's binding to mail server, there is no default value, example value 'smtp://user:pass@mailserver.examples.com:25/'
     - MAIL_FROM: wekan's admin email address, no default value, example value 'wekan-admin@example.com'

confinement: strict
grade: devel

apps:
    wekan:
        command: wekan-control start_node
        daemon: simple
        plugs: [network, network-bind]

    mongodb:
        command: mongodb-control
        daemon: simple
        plugs: [network, network-bind]

    start:
        command: wekan-control start
        plugs: [network, network-bind]

    stop:
        command: wekan-control stop
        plugs: [network, network-bind]

    status:
        command: wekan-control status
        plugs: [network, network-bind]

    restart:
        command: wekan-control restart
        plugs: [network, network-bind]

    help:
        command: wekan-help help

parts:
    wekan:
        source: https://github.com/wekan/wekan/releases/download/v0.10.1/wekan-0.10.1.tar.gz
        plugin: dump
        organize:
            README: README.wekan
        stage:
            - -README

    nodejs:
        source: parts/wekan/install/programs/server/
        plugin: nodejs
        node-packages: [npm]
        node-engine: 0.10.40
        after: [mongodb, wekan]
        organize:
            lib/node_modules/meteor-dev-bundle/npm-shrinkwrap.json: programs/server/npm-shrinkwrap.json
            lib/node_modules/meteor-dev-bundle/node_modules: programs/server/node_modules

    helpers:
        source: src
        plugin: dump
        organize:
            wekan-control: bin/wekan-control
            mongodb-control: bin/mongodb-control
            wekan-read-settings: bin/wekan-read-settings
            wekan-help: bin/wekan-help
            config: bin/config
            configure: meta/hooks/configure
